#!/usr/bin/env bash

install() {
  link "$REPOSITORY_ROOT/.xinitrc" ~/.xinitrc
  link "$REPOSITORY_ROOT/urxvt-extensions" ~/.urxvt/ext
  link "$REPOSITORY_ROOT/urxvt-themes" ~/.urxvt/themes
  setup_submodules
}

source <(curl -Lfs https://git.io/lnkr)
